In [1]:
!pip install numpy


   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   ------------- -------------------------- 4.2/12.8 MB 14.8 MB/s eta 0:00:01
   ---------------- ----------------------- 5.2/12.8 MB 15.2 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.8 MB 13.4 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 14.3 MB/s eta 0:00:00


In [23]:
import numpy as np

var1 = np.array([1,2,3,4,5,6])
# print(var1)
# print(type(var1))
print(var1.reshape(1,6))

[[1 2 3 4 5 6]]


In [ ]:
var2 = np.array([[1,23,5,46,8],[1,2,3,4,5,]])
print(var2)
print(var2.shape)



[[ 1 23  5 46  8]
 [ 1  2  3  4  5]]


ValueError: cannot reshape array of size 10 into shape (1,5)

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.arange(1,5)

array([1, 2, 3, 4])

In [19]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])